version: "3"
services:
  web: # the name of the service is 'web'
    image: ashburnere/hello-python-docker:v1 # username/repo:tag of the image to pull
    deploy:
      replicas: 5  # run 5 instances of that image
      resources:
        limits:
          cpus: "0.1" # limit each instance to use, at most, 10% of a single core of CPU time
          memory: 50M # limit each instance to use, at most 50MB RAM
      restart_policy:
        condition: on-failure 
    ports:
      - "4000:80" # map port 4000 on the host to web’s port 80
    networks:
      - webnet # instruct web’s containers to share port 80 via a load-balanced network called webnet
networks: # define the webnet network with the default settings (which is a load-balanced overlay network).
  webnet:

